name: weather_app
description: Test of concept in Flutter, on weather application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  geolocator: ^8.2.1
  intl: ^0.17.0
  google_maps_flutter: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 
  build_runner:
  flutter_launcher_icons: '0.9.2'
  flutter_native_splash: '2.1.6'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_icons:
  adaptive_icon_background: 'assets/images/launcher_background.png'
  adaptive_icon_foreground: 'assets/images/launcher_foreground.png'
  image_path_ios: 'assets/images/launcher.png'
  image_path_android: 'assets/images/launcher.png'
  android: true
  ios: true

flutter_native_splash:
  image: 'assets/images/splash.png'
  color: '#ffffff'
  image_dark: 'assets/images/splash.png'
  color_dark: '#ffffff'
