// Mocks generated by Mockito 5.1.0 from annotations
// in weather/test/features/map/domain/usecases/get_map_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/data/datasources/map_remote_data_source.dart'
    as _i3;
import 'package:weather_app/data/models/map_model.dart' as _i2;

class _FakeMapModel_0 extends _i1.Fake implements _i2.MapModel {}

class MockMapRemoteDataSource extends _i1.Mock
    implements _i3.MapRemoteDataSource {
  MockMapRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MapModel> getMaps(
          String? mapType, int? x, int? y, int? zoom) =>
      (super.noSuchMethod(Invocation.method(#getMaps, [mapType, x, y, zoom]),
              returnValue: Future<_i2.MapModel>.value(_FakeMapModel_0()))
          as _i4.Future<_i2.MapModel>);
}
