// Mocks generated by Mockito 5.1.0 from annotations
// in weather/test/features/weather/domain/usecases/get_weather_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/utils/failures.dart' as _i6;
import 'package:weather_app/utils/get_lat_long.dart' as _i9;
import 'package:weather_app/usescase/weather_params.dart' as _i8;
import 'package:weather_app/data/repository/weather_repository.dart' as _i2;
import 'package:weather_app/utils/lat_long.dart' as _i10;
import 'package:weather_app/data/entities/weather.dart' as _i7;
import 'package:weather_app/usescase/get_weather.dart' as _i4;

class _FakeWeatherRepository_0 extends _i1.Fake
    implements _i2.WeatherRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class MockGetWeather extends _i1.Mock implements _i4.GetWeather {
  MockGetWeather() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeWeatherRepository_0()) as _i2.WeatherRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Weather>> call(
          _i8.WeatherParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Weather>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Weather>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Weather>>);
}

class MockGetLatLongImpl extends _i1.Mock implements _i9.GetLatLongImpl {
  MockGetLatLongImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.LatLong>> getLatLong() =>
      (super.noSuchMethod(Invocation.method(#getLatLong, []),
              returnValue: Future<_i3.Either<_i6.Failure, _i10.LatLong>>.value(
                  _FakeEither_1<_i6.Failure, _i10.LatLong>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i10.LatLong>>);
}
